def num(): # 88005553535
    print(8, end='')
    print(8, end='')
    print(0, end='')
    print(0, end='')
    print(5, end='')
    print(5, end='')
    print(5, end='')
    print(3, end='')
    print(5, end='')
    print(3, end='')
    print(5, end='')
num()
